require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '11.0'

target 'TelemetricMain' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'TelemetricMainTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'TelemetricMain-tvOS' do
  # Pods for TelemetricMain-tvOS

  target 'TelemetricMain-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end